version: '3.7'

services:
  zoo1:
    image: zookeeper:3.4.9
    hostname: zoo1
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - "2181:2181"
    environment:
      ZOO_MY_ID: 1
      ZOO_PORT: 2181
      ZOO_SERVERS: server.1=zoo1:2888:3888
  kafka:
    image: confluentinc/cp-kafka:5.5.1
    hostname: kafka1
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka:29092,LISTENER_DOCKER_EXTERNAL://127.0.0.1:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zoo1:2181"
      KAFKA_CREATE_TOPICS: notification:1:1:compact
      KAFKA_BROKER_ID: 1
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zoo1
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
  # docker run -p 8081:8080 -e KAFKA_BROKERS=host.docker.internal:19092 quay.io/cloudhut/kowl:master

  kowl:
    image: quay.io/cloudhut/kowl:master
    ports:
      - "8099:8080"
    environment:
      - KAFKA_BROKERS=kafka:29092
    depends_on:
      - kafka
  # producer-service:
  #   image: producer
  #   build: ./producer-service
  #   container_name: producer
  #   ports:
  #     - "8009:8080"
  #   healthcheck:
  #     test: ... # Command to check health.
  #     interval: 5s # Interval between health checks.
  #     timeout: 5s # Timeout for each health checking.
  #     retries: 20 # Hou many times retries.
  #     start_period: 10s # Estimated time to boot.
  #   depends_on:
  #     - kafka
  #   environment:
  #     - spring.kafka.bootstrap-servers=kafka:29092
  #     - spring.profiles.active=default,docker
